Repository antvis/scale, pull requests merged in 2020-12, with the labels that each got.

#66 chore: add src to files for sourceMap
  package.json
Labels: PR: unreviewed

#67 feat: 日常发布
  CHANGELOG.md
  package.json
Labels: PR: reviewed-approved

#68 chore: export Tick
  package.json
  src/index.ts
Labels: PR: partially-approved
