Repository antvis/scale, pull requests merged in 2020-02, with the labels that each got.

#29 feat(scale): add quantile, quantize scales
  README.md
  src/continuous/quantile.ts
  src/continuous/quantize.ts
  src/index.ts
  src/tick-method/quantile.ts
  tests/unit/quantile-spec.ts
  tests/unit/quantize-spec.ts
  tests/unit/tick-method/quantile-spec.ts
Labels: PR: reviewed-approved, enhancement

#30 Support interval
  package.json
  src/tick-method/linear.ts
  src/tick-method/r-prettry.ts
  src/util/interval.ts
  tests/unit/tick-method/linear-spec.ts
  tests/unit/util/interval-spec.ts
Labels: PR: reviewed-approved

#33 chore: v0.3.0
  package.json
Labels: PR: reviewed-approved, chore

#34 fix: fix auto/number when min < 0 and interval is null
  CHANGELOG.md
  package.json
  src/auto/number.js
  test/unit/auto/number-spec.js
Labels: bug
