Repository antvis/scale, pull requests merged in 2020-03, with the labels that each got.

#35 feat: support d3-linear tick method
  src/tick-method/d3-linear.ts
  src/tick-method/index.ts
  src/util/d3-linear.ts
  tests/unit/util/d3-linear-spec.ts
Labels: enhancement

#36 feat: support minLimit/maxLimit
  package.json
  src/base.ts
  src/continuous/base.ts
  src/tick-method/d3-linear.ts
  src/tick-method/linear.ts
  src/tick-method/r-prettry.ts
  src/types.ts
  src/util/strict-limit.ts
  tests/unit/linear-spec.ts
  tests/unit/util/strict-limit-spec.ts
Labels: PR: reviewed-approved, enhancement

#39 fix: simplify strict-limit default limit
  src/tick-method/d3-linear.ts
  src/tick-method/linear.ts
  src/tick-method/r-prettry.ts
  src/util/strict-limit.ts
Labels: PR: reviewed-changes-requested, bug

#40 fix: category scale 在做 scale 时，对超出范围的数据不返还 NaN
  src/category/base.ts
  tests/unit/category-spec.ts
  tests/unit/time-cat-spec.ts
Labels: PR: unreviewed, bug

#41 fix: fix tslint error & run lint on CI
  package.json
  src/util/d3-linear.ts
Labels: PR: reviewed-changes-requested, bug

#42 fix(ticks): very little values ticks error
  package.json
  src/auto/number.js
  test/unit/auto/number-spec.js
Labels: bug
