Repository antvis/scale, pull requests merged in 2020-07, with the labels that each got.

#57 fix: 修改 timeCat类型scale type
  src/category/time.ts
  tests/unit/time-cat-spec.ts
Labels: PR: unreviewed, bug

#58 chore: release 0.3.2
  package.json
Labels: PR: unreviewed, chore

#61 feat: 增加registerTickMethod扩展api
  src/index.ts
  src/tick-method/index.ts
  tests/unit/index-spec.ts
Labels: PR: partially-approved, enhancement
