Repository antvis/scale, pull requests merged in 2021-04, with the labels that each got.

#77 Feat/constant
  .eslintrc.js
  __tests__/unit/scales/base.spec.ts
  __tests__/unit/scales/constant.spec.ts
  src/index.ts
  src/scales/base.ts
  src/scales/constant.ts
  src/scales/identity.ts
  src/types.ts
Labels: PR: reviewed-approved

#78 refactor(type): extract TickOptions from BaseOptions
  __tests__/unit/scales/base.spec.ts
  __tests__/unit/scales/constant.spec.ts
  __tests__/unit/scales/identity.spec.ts
  __tests__/unit/tick-methods/baisc.spec.ts
  src/scales/base.ts
  src/scales/constant.ts
  src/scales/identity.ts
  src/types.ts
Labels: PR: reviewed-approved

#79 feat: finish category scale
  .gitignore
  __tests__/unit/scales/category.spec.ts
  __tests__/unit/tick-methods/basic.spec.ts
  package.json
  src/scales/category.ts
  src/types.ts
Labels: PR: reviewed-approved

#82 feat: finish category scale
  .gitignore
  __tests__/unit/scales/category.spec.ts
  __tests__/unit/tick-methods/basic.spec.ts
  package.json
  src/scales/category.ts
  src/types.ts
Labels: PR: unreviewed

#84 refactor(base): add getDefaultOptions to override defualt options
  .eslintrc.js
  __tests__/unit/scales/base.spec.ts
  src/scales/base.ts
  src/scales/category.ts
  src/scales/constant.ts
  src/scales/identity.ts
Labels: PR: reviewed-approved

#85 Docs/readme
  README.md
  README.zh-CN.md
  docs/identity.md
Labels: PR: reviewed-approved

#86 Feat/continuous
  .eslintrc.js
  __tests__/unit/scales/base.spec.ts
  __tests__/unit/scales/constant.spec.ts
  __tests__/unit/scales/continuous.spec.ts
  __tests__/unit/scales/identity.spec.ts
  __tests__/unit/tick-methods/basic.spec.ts
  __tests__/unit/utils/bisect.spec.ts
  __tests__/unit/utils/clamp.spec.ts
  __tests__/unit/utils/compose.spec.ts
  __tests__/unit/utils/interpolate.spec.ts
  __tests__/unit/utils/normalize.spec.ts
  package.json
  src/scales/base.ts
  src/scales/constant.ts
  src/scales/continuous.ts
  src/scales/identity.ts
  src/types.ts
  src/utils/bisect.ts
  src/utils/clamp.ts
  src/utils/compose.ts
  src/utils/index.ts
  src/utils/interpolate.ts
  src/utils/normalize.ts
Labels: PR: reviewed-approved

#90 Docs/constant
  README.md
  __tests__/unit/scales/constant.spec.ts
  __tests__/unit/scales/continuous.spec.ts
  docs/constant.md
  docs/identity.md
  package.json
  src/scales/constant.ts
  src/types.ts
Labels: PR: reviewed-approved

#87 docs(category): update category docs
  README.md
  docs/category.md
Labels: PR: reviewed-approved

#88 feat(point): finish point scale
  .eslintrc.js
  .github/workflows/build.yml
  README.md
  __tests__/test-utils/benchmark.ts
  __tests__/unit/scales/band.spec.ts
  __tests__/unit/scales/category.spec.ts
  __tests__/unit/scales/point.spec.ts
  __tests__/unit/utils/sequence.spec.ts
  commitlint.config.js
  docs/band.md
  docs/point.md
  src/scales/band.ts
  src/scales/category.ts
  src/scales/point.ts
  src/types.ts
  src/utils/sequence.ts
  tsconfig.json
Labels: PR: reviewed-approved

#83 feat: finish band scale
  README.md
Labels: PR: partially-approved

#91 Docs/unify
  docs/band.md
  docs/category.md
  docs/constant.md
  docs/identity.md
  docs/point.md
Labels: PR: reviewed-approved

#92 feat(linear): finish linear scale
  .eslintrc.js
  README.md
  __tests__/perf/band.spec.ts
  __tests__/perf/benchmark.ts
  __tests__/perf/category.spec.ts
  __tests__/unit/scales/band.spec.ts
  __tests__/unit/scales/category.spec.ts
  __tests__/unit/scales/constant.spec.ts
  __tests__/unit/scales/continuous.spec.ts
  __tests__/unit/scales/identity.spec.ts
  __tests__/unit/scales/linear.spec.ts
  __tests__/unit/scales/point.spec.ts
  __tests__/unit/tick-methods/linear.spec.ts
  __tests__/unit/utils/d3-linear-nice.spec.ts
  __tests__/unit/utils/wilkinson-extended.spec.ts
  docs/linear.md
  src/scales/band.ts
  src/scales/category.ts
  src/scales/continuous.ts
  src/scales/linear.ts
  src/scales/point.ts
  src/tick-method/linear.ts
  src/types.ts
  src/utils/d3-linear-nice.ts
  src/utils/wilkinson-extended.ts
Labels: PR: reviewed-approved

#95 Feat/threshold
  README.md
  __tests__/unit/scales/band.spec.ts
  __tests__/unit/scales/point.spec.ts
  __tests__/unit/scales/threshold.spec.ts
  docs/threshold.md
  src/index.ts
  src/scales/threshold.ts
  src/types.ts
Labels: PR: unreviewed

#97 feat(sqrt): finish sqrt scale
  __tests__/unit/scales/sqrt.spec.ts
  docs/sqrt.md
  src/scales/sqrt.ts
  src/types.ts
Labels: PR: unreviewed

#98 docs: fix
  README.md
Labels: PR: partially-approved

#99 Docs/fix
  README.md
  docs/linear.md
  docs/sqrt.md
Labels: PR: partially-approved

#100 Chore/workflow
  .github/workflows/build.yml
  README.md
Labels: PR: unreviewed

#101 fix: fix the bug that the array spacing is not the same
  __tests__/bugs/issue-53.spec.ts
  __tests__/unit/scales/linear.spec.ts
  __tests__/unit/tick-methods/linear.spec.ts
  __tests__/unit/utils/wilkinson-extended.spec.ts
  src/utils/wilkinson-extended.ts
Labels: PR: partially-approved

#102 Feat/quantize
  README.md
  __tests__/unit/scales/continuous.spec.ts
  __tests__/unit/scales/identity.spec.ts
  __tests__/unit/scales/linear.spec.ts
  __tests__/unit/scales/pow.spec.ts
  __tests__/unit/scales/quantize.spec.ts
  __tests__/unit/tick-methods/basic.spec.ts
  __tests__/unit/tick-methods/linear.spec.ts
  __tests__/unit/tick-methods/pretty.spec.ts
  __tests__/unit/tick-methods/wilkinson-extended.spec.ts
  __tests__/unit/utils/wilkinson-extended.spec.ts
  docs/scales/band.md
  docs/scales/category.md
  docs/scales/constant.md
  docs/scales/identity.md
  docs/scales/linear.md
  docs/scales/point.md
  docs/scales/pow.md
  docs/scales/quantize.md
  docs/scales/sqrt.md
  docs/scales/threshold.md
  docs/tickMethods/pretty.md
  docs/tickMethods/wilkinson-extended.md
  src/index.ts
  src/scales/continuous.ts
  src/scales/identity.ts
  src/scales/linear.ts
  src/scales/pow.ts
  src/scales/quantize.ts
  src/scales/sqrt.ts
  src/scales/threshold.ts
  src/tick-method/basic.ts
  src/tick-method/linear.ts
  src/tick-method/pow.ts
  src/tick-methods/pretty.ts
  src/tick-methods/wilkinson-extended.ts
  src/types.ts
  src/utils/calculate-base.ts
  src/utils/index.ts
  src/utils/interpolate.ts
Labels: PR: partially-approved

#106 fix: fix wrong usage for toBeCloseTo() API
  __tests__/unit/scales/band.spec.ts
  __tests__/unit/scales/pow.spec.ts
Labels: PR: reviewed-approved

#105 Feat/ordinal
  README.md
  __tests__/perf/band.spec.ts
  __tests__/perf/ordinal.spec.ts
  __tests__/unit/scales/band.spec.ts
  __tests__/unit/scales/base.spec.ts
  __tests__/unit/scales/continuous.spec.ts
  __tests__/unit/scales/ordinal.spec.ts
  __tests__/unit/scales/point.spec.ts
  docs/quantize.md
  docs/scales/category.md
  docs/scales/ordinal.md
  src/index.ts
  src/scales/band.ts
  src/scales/ordinal.ts
  src/types.ts
Labels: PR: reviewed-approved

#103 feat: finish log scale
  README.md
  __tests__/unit/scales/linear.spec.ts
  __tests__/unit/scales/log.spec.ts
  __tests__/unit/scales/ordinal.spec.ts
  __tests__/unit/scales/point.spec.ts
  docs/scales/log.md
  docs/tick-methods/pretty.md
  docs/tick-methods/wilkinson-extended.md
  src/index.ts
  src/scales/log.ts
  src/types.ts
Labels: PR: unreviewed

#108 feat: finish quartile scale
  __tests__/unit/scales/quantile.spec.ts
  __tests__/unit/utils/create-quartile.spec.ts
  docs/quantize.md
  docs/scales/band.md
  docs/scales/constant.md
  docs/scales/identity.md
  docs/scales/linear.md
  docs/scales/log.md
  docs/scales/ordinal.md
  docs/scales/point.md
  docs/scales/pow.md
  docs/scales/quantile.md
  docs/scales/quantize.md
  docs/scales/sqrt.md
  docs/scales/threshold.md
  src/index.ts
  src/scales/quantile.ts
  src/scales/quantize.ts
  src/types.ts
  src/utils/create-quartile.ts
Labels: PR: reviewed-approved

#110 Refactor/scales
  .eslintrc.js
  __tests__/unit/scales/band.spec.ts
  __tests__/unit/scales/point.spec.ts
  __tests__/unit/scales/sqrt.spec.ts
  docs/scales/band.md
  docs/scales/ordinal.md
  docs/scales/point.md
  src/index.ts
  src/scales/band.ts
  src/scales/base.ts
  src/scales/continuous.ts
  src/scales/ordinal.ts
  src/scales/point.ts
  src/scales/pow.ts
  src/scales/quantile.ts
  src/scales/quantize.ts
  src/scales/sqrt.ts
  src/scales/threshold.ts
  src/types.ts
Labels: PR: partially-approved

#112 docs(readme): add Quantile and remove some scales
  README.md
Labels: PR: reviewed-approved

#111 feat: finish linear ticks and pow ticks
  __tests__/bugs/issue-53.spec.ts
  __tests__/unit/scales/linear.spec.ts
  __tests__/unit/scales/pow.spec.ts
  __tests__/unit/tick-methods/linear.spec.ts
  src/scales/linear.ts
  src/scales/pow.ts
  src/tick-methods/linear.ts
  src/utils/d3-linear-nice.ts
  src/utils/tick-utils.ts
  tsconfig.json
Labels: PR: reviewed-approved

#115 refactor: remove formatter options
  __tests__/unit/scales/band.spec.ts
  __tests__/unit/scales/base.spec.ts
  __tests__/unit/scales/constant.spec.ts
  __tests__/unit/scales/continuous.spec.ts
  __tests__/unit/scales/identity.spec.ts
  __tests__/unit/scales/quantile.spec.ts
  __tests__/unit/scales/quantize.spec.ts
  __tests__/unit/scales/threshold.spec.ts
  docs/scales/band.md
  docs/scales/constant.md
  docs/scales/identity.md
  docs/scales/linear.md
  docs/scales/log.md
  docs/scales/ordinal.md
  docs/scales/point.md
  docs/scales/pow.md
  docs/scales/quantile.md
  docs/scales/quantize.md
  docs/scales/sqrt.md
  docs/scales/threshold.md
  src/scales/base.ts
  src/types.ts
Labels: PR: reviewed-approved

#116 refactor: unify scale flow and simplify code
  __tests__/unit/scales/base.spec.ts
  __tests__/unit/scales/continuous.spec.ts
  src/scales/band.ts
  src/scales/base.ts
  src/scales/constant.ts
  src/scales/continuous.ts
  src/scales/identity.ts
  src/scales/linear.ts
  src/scales/log.ts
  src/scales/ordinal.ts
  src/scales/point.ts
  src/scales/pow.ts
  src/scales/quantile.ts
  src/scales/quantize.ts
  src/scales/sqrt.ts
  src/scales/threshold.ts
  src/types.ts
Labels: PR: partially-approved

#117 fix: fix extended-algorithm accuracy problem
  __tests__/unit/tick-methods/wilkinson-extended.spec.ts
  __tests__/unit/utils/add.spec.ts
  src/tick-methods/wilkinson-extended.ts
  src/utils/precision-add.ts
Labels: PR: unreviewed

#120 Feat/time
  README.md
  __tests__/unit/scales/continuous.spec.ts
  __tests__/unit/scales/linear.spec.ts
  __tests__/unit/scales/log.spec.ts
  __tests__/unit/scales/pow.spec.ts
  __tests__/unit/scales/quantile.spec.ts
  __tests__/unit/scales/quantize.spec.ts
  __tests__/unit/scales/time.spec.ts
  __tests__/unit/tick-methods/d3-linear.spec.ts
  __tests__/unit/tick-methods/d3-time.spec.ts
  __tests__/unit/tick-methods/r-pretty.spec.ts
  __tests__/unit/utils/choose-mask.spec.ts
  __tests__/unit/utils/d3-linear-nice.spec.ts
  __tests__/unit/utils/d3-time-nice.spec.ts
  __tests__/unit/utils/is-valid.spec.ts
  __tests__/unit/utils/time-duration.spec.ts
  __tests__/unit/utils/time-interval.spec.ts
  __tests__/unit/utils/utc-interval.spec.ts
  docs/scales/time.md
  package.json
  src/index.ts
  src/scales/continuous.ts
  src/scales/log.ts
  src/scales/quantile.ts
  src/scales/quantize.ts
  src/scales/threshold.ts
  src/scales/time.ts
  src/tick-methods/d3-linear.ts
  src/tick-methods/d3-time.ts
  src/types.ts
  src/utils/choose-mask.ts
  src/utils/d3-linear-nice.ts
  src/utils/d3-time-nice.ts
  src/utils/index.ts
  src/utils/is-valid.ts
  src/utils/time-interval.ts
  src/utils/utc-interval.ts
Labels: PR: reviewed-approved

#119 perf: improve fixed-length array performance
  __tests__/unit/utils/sequence.spec.ts
  src/tick-methods/wilkinson-extended.ts
  src/utils/sequence.ts
Labels: PR: partially-approved

#123 chore: change tick-count from 10 to 5
  __tests__/unit/scales/continuous.spec.ts
  __tests__/unit/scales/log.spec.ts
  __tests__/unit/scales/quantile.spec.ts
  __tests__/unit/scales/quantize.spec.ts
  __tests__/unit/scales/time.spec.ts
  __tests__/unit/utils/d3-linear-nice.spec.ts
  src/scales/continuous.ts
  src/scales/log.ts
  src/scales/quantile.ts
  src/scales/quantize.ts
  src/scales/time.ts
  src/utils/d3-linear-nice.ts
Labels: PR: unreviewed

#124 Feat scale version
  package.json
Labels: PR: unreviewed

#126 chore(index): expose useful API
  src/index.ts
Labels: PR: partially-approved

#127 docs: update readme
  README.md
  package.json
Labels: PR: reviewed-approved

#128 chore: align center
  README.md
Labels: PR: reviewed-approved

#129 docs: add descriptions for scales in README.md
  README.md
Labels: PR: reviewed-approved
