Repository antvis/scale, pull requests merged in 2021-06, with the labels that each got.

#150 refactor: make parameter names more descriptive
  src/types.ts
Labels: PR: reviewed-approved

#151 docs: add examples' image and some difference between tick methods
  README.md
  docs/api/tick-methods.md
  tsconfig.json
Labels: PR: partially-approved

#152 refactor(threshold): search from thresholds instead of getDomain()
  src/scales/quantile.ts
  src/scales/quantize.ts
  src/scales/threshold.ts
Labels: PR: reviewed-approved

#153 refactor(qunantile): remove useless code to increase test coverage
  src/scales/quantile.ts
Labels: PR: reviewed-approved

#154 Feat/export
  __tests__/unit/scales/continuous.spec.ts
  __tests__/unit/tick-methods/d3-log.spec.ts
  __tests__/unit/tick-methods/d3-time.spec.ts
  src/index.ts
  src/scales/band.ts
  src/scales/ordinal.ts
  src/scales/pow.ts
  src/scales/threshold.ts
Labels: PR: reviewed-approved

#155 chore: update version to 0.4.1
  package.json
Labels: PR: reviewed-approved

#157 fix: pretty wilkinson-extended with precision problem close: #156
  __tests__/unit/tick-methods/wilkinson-extended.spec.ts
  __tests__/unit/utils/add.spec.ts
  package.json
  src/tick-methods/wilkinson-extended.ts
  src/utils/precision-add.ts
Labels: PR: unreviewed

#158 fix: precision problem in extended in v0.3.x
  package.json
  src/util/extended.ts
  tests/unit/tick-method/quantile-spec.ts
  tests/unit/util/extended-spec.ts
Labels: PR: unreviewed

#160 feat/ordinal: support date input
  __tests__/unit/scales/ordinal.spec.ts
  docs/api/scales/band.md
  docs/api/scales/ordinal.md
  docs/api/scales/point.md
  package.json
  src/scales/ordinal.ts
  src/tick-methods/d3-log.ts
  src/types.ts
Labels: PR: reviewed-approved
