Repository antvis/scale, pull requests merged in 2021-05, with the labels that each got.

#136 feat/time
  __tests__/unit/scales/base.spec.ts
  __tests__/unit/scales/time.spec.ts
  __tests__/unit/tick-methods/d3-time.spec.ts
  __tests__/unit/utils/bisect.spec.ts
  __tests__/unit/utils/d3-time-nice.spec.ts
  __tests__/unit/utils/ticks.spec.ts
  __tests__/unit/utils/time-interval.spec.ts
  __tests__/unit/utils/utc-interval.spec.ts
  src/index.ts
  src/scales/time.ts
  src/tick-methods/d3-linear.ts
  src/tick-methods/d3-time.ts
  src/utils/bisect.ts
  src/utils/d3-linear-nice.ts
  src/utils/d3-time-nice.ts
  src/utils/find-tick-interval.ts
  src/utils/index.ts
  src/utils/ticks.ts
  src/utils/time-interval.ts
  src/utils/utc-interval.ts
Labels: PR: partially-approved

#141 docs(readme): add emoji for contribution
  README.md
  __tests__/unit/tick-methods/d3-log.spec.ts
  __tests__/unit/tick-methods/wilkinson-extended.spec.ts
Labels: PR: unreviewed

#142 fix(extended): fix extended algorithm Infinite loop for NaN
  src/util/extended.ts
  src/util/math.ts
  tests/bugs/issue-3413-spec.ts
  tests/unit/util/extended-spec.ts
  tslint.json
Labels: PR: partially-approved

#144 chore: update version 0.4.0
  package.json
Labels: PR: reviewed-approved

#145 ci(action): add deps cache support based on package.json
  .github/workflows/build.yml
Labels: PR: partially-approved

#146 docs(api): fix
  docs/api/readme.md
Labels: PR: reviewed-approved

#147 docs(linear): add polymap usage
  docs/api/scales/linear.md
Labels: PR: partially-approved
